from openai import OpenAI

from string import Template
import argparse
import os
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from analytics.graph import TelemetryGraph

import datetime



PROMPT_TRACE_ONLY = Template("""\
You are an assistant that generates a written handover report about the current state of a video game task. \
In this task, players must care for "patient" non-player characters (NPCs) by tracking which "potions" they each need, and (separately) delivering requests to and from other characters located around the game world. \
The purpose of this report is to detail the user's progress and game knowledge in order to help another player \
                  continue the task from where the user left off as efficiently as possible. \
Assume the reader of this report has no prior knowledge of the task. \
You have access to a knowledge graph representing data from the game telemetry of the player's session. \
Note that the game telemetry represents only some of the information that the player has learned about the game, and may not include all relevant details. \
For example, players can hold only one potion at a time; if they picked up another one, the previous one must have been put back or delivered.
Your role is to use this information to compose a complete and accurate report that can be used to efficiently continue the task. \
                  
The current knowledge graph is:
```
$knowledge_graph
```
""")

PROMPT_WITH_REPORT = Template("""\
You are an assistant that generates a written handover report about the current state of a video game task. \
In this task, players must care for "patient" non-player characters (NPCs) by tracking which "potions" they each need, and (separately) delivering requests to and from other characters located around the game world. \
The purpose of this report is to detail the user's progress and game knowledge in order to help another player\
                  continue the task from where the user left off as efficiently as possible.\
Assume the reader of this report has no prior knowledge of the task. \
You have access to a 1. a knowledge graph representing data from the game telemetry of the player's session, and 2. the notes that the user themselves has written for the next player. \
Note that the game telemetry provides only some of the information that the player has learned about the game, and may not include all relevant details. \
For example, players can hold only one potion at a time; if they picked up another one, the previous one must have been put back or delivered.
                              
Your role is to combine this information to compose a complete and accurate report that can be used by a new player to efficiently continue the task.
                  
The current knowledge graph is:
```
$knowledge_graph
```
The user's notes are:
$report
""")

PROMPT_WITH_BOTH_REPORTS = Template("""\
You are an assistant that generates a written handover report about the current state of a video game task. \
In this task, players must care for "patient" non-player characters (NPCs) by tracking which "potions" they each need, and (separately) delivering requests to and from other characters located around the game world. \
The purpose of this report is to detail the user's progress and game knowledge in order to help another player\
                  continue the task from where the user left off as efficiently as possible.\
Assume the reader of this report has no prior knowledge of the task. \
You have access to 1. the notes that the user themselves has written for the next player, and 2. a report generated by an AI assistant based on the game's telemetry.\
Note that the game telemetry provides only some of the information that the player has learned about the game, and may not include all relevant details. \
                                    
Your role is to synthesize this information to compose a complete and accurate report that can be used to efficiently continue the task.
               
The user's notes are:
$report

The AI-generated report based on telemetry is:
$telemetry_report
""")


def generate_graph(telemetry_file):
    g = TelemetryGraph()
    g.parse_from_file(telemetry_file)
    return g

def retrieve_user_report(report_file):
    with open(report_file, 'r') as f:
        report = f.read()
    return report

def save_knowledge_graph(g, save_file):
    with open(save_file, 'w') as f:
        f.write(str(g))

def save_generated_report(report, save_file):
    with open(save_file, 'w') as f:
        f.write(report)

def get_gpt_response(prompt):
    client = OpenAI(api_key=os.environ.get('OPENAI_API_KEY'))
    model = os.environ.get('GPT_MODEL', 'gpt-4o-mini-2024-07-18')
    response = client.completions.create(
        model=model,
        prompt=prompt,
        max_tokens=1500,
        temperature=0,
        n=1,
        stop=None
    )
    return response.choices[0].text.strip()

def generate_report(pid, telemetry_dir, report_dir, save_dir, mode="hybrid"):
    # Generate the knowledge graph
    telemetry_file = os.path.join(telemetry_dir, f"{pid}.txt")
    g = generate_graph(telemetry_file)
    graph_save_file = os.path.join(save_dir, f"{pid}_knowledge_graph.txt")
    save_knowledge_graph(g, graph_save_file)

    # Generate the final report
    if mode == "hybrid":

    # Retrieve the user's report
        report_file = os.path.join(report_dir, f"{pid}_user_report.txt")
        report = retrieve_user_report(report_file)
        prompt = PROMPT_WITH_REPORT.substitute(knowledge_graph=str(g), report=report)
    
    else:
        prompt = PROMPT_TRACE_ONLY.substitute(knowledge_graph=str(g))

    # Use OpenAI API to generate the report
    response = get_gpt_response(prompt)

    now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    response += f"\n\n[This report generated at {now}]\n"
    response += "[Generated using: model={}, temperature=0, max_tokens=1500]\n".format(os.environ.get('GPT_MODEL', 'gpt-4o-mini-2024-07-18'))
    
    # Save the generated report
    if mode == "hybrid":
        save_file = os.path.join(save_dir, f"{pid}_hybrid_report_{now}.txt")
    else:
        save_file = os.path.join(save_dir, f"{pid}_generated_report_{now}.txt")
    
    
    save_generated_report(response, save_file)

def get_latest_generated_report(report_dir, pid):
    # List all generated reports for the participant
    reports = [f for f in os.listdir(report_dir) if f.startswith(f"{pid}_generated_report") and f.endswith(".txt")]
    
    if not reports:
        return None  # No generated reports found
    
    # Sort reports by timestamp in filename (assuming format: {pid}_generated_report_{timestamp}.txt)
    reports.sort(key=lambda x: x.split('_')[-1], reverse=True)  # Sort by timestamp, latest first
    
    latest_report_file = os.path.join(report_dir, reports[0])
    
    with open(latest_report_file, 'r') as f:
        latest_report = f.read()
    
    return reports[0], latest_report

def generate_combined_report(pid, report_dir):
    llm_report_filename, llm_report = get_latest_generated_report(report_dir, pid)
    if llm_report is None:
        print(f"No LLM-generated report found for participant {pid}. Cannot generate combined report.")
        return

    user_report = retrieve_user_report(os.path.join(report_dir, f"{pid}_user_report.txt"))

    prompt = PROMPT_WITH_BOTH_REPORTS.substitute(report=user_report, telemetry_report=llm_report)
    combined_report = get_gpt_response(prompt)
    now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    combined_report += f"\n\n[This combined report generated at {now} from user report and llm-generated file {llm_report_filename}]\n"
    combined_report += "[Generated using: model={}, temperature=0, max_tokens=1500]\n".format(os.environ.get('GPT_MODEL', 'gpt-4o-mini-2024-07-18'))

    save_file = os.path.join(report_dir, f"{pid}_combined_report_{now}.txt")
    save_generated_report(combined_report, save_file)

# if __name__ == "__main__":
#     data_dir = os.environ.get('DATA_DIR')
#     report_dir = os.path.join(data_dir, 'participant_data')
#     telemetry_dir = os.path.join(report_dir, 'telemetry')
#     save_dir = os.path.join(data_dir, 'reports')

#     for pid in range(501, 510):
#         pid = str(pid)
#         generate_report(pid, telemetry_dir, report_dir, save_dir)
    # main(502, telemetry_dir, report_dir, save_dir)  # Example for a single participant

if __name__ == "__main__":
    from dotenv import load_dotenv
    load_dotenv()

    parser = argparse.ArgumentParser(description="Generate a hybrid report for a video game task.")
    parser.add_argument("pid", type=str, help="Participant ID")
    parser.add_argument("--telemetry_dir", type=str, required=True, help="Directory containing telemetry files")
    parser.add_argument("--report_dir", type=str, required=False, help="Directory containing user reports")
    parser.add_argument("--save_dir", type=str, required=True, help="Directory to save the generated report")
    parser.add_argument("--mode", type=str, choices=["hybrid", "trace_only"], default="trace_only", help="Mode of report generation")

    args = parser.parse_args()

    generate_report(args.pid, args.telemetry_dir, args.report_dir, args.save_dir, args.mode)